version: 2
references:
  container_config: &container_config
    docker:
      - image: circleci/node:12
    working_directory: ~/rc-ui
  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/rc-ui
jobs:
  setup:
    steps:
      <<: *container_config
      - checkout
      - run: node -v
      - run: yarn -v
      - run: yarn install
      - persist_to_workspace:
        root: ~/rc-ui
        paths:
          - node_modules
      - store_artifacts:
        path: yarn.lock
  lint:
    steps:
      <<: *container_config
      - checkout
      - *attach_workspace
      - run: yarn run lint
  test:
    steps:
      <<: *container_config
      environment:
        CI: true
      - checkout
      - *attach_workspace
      -run: yarn run test:ci
  dist:
    steps:
      <<: *container_config
      - checkout
      - *attach_workspace
      - run: yarn run build
workflows:
  version: 2
  build_test:
    jobs:
      - setup:
          filters:
            branches:
              ignore: gh-pages
      - lint:
        requires:
          - setup
      - test:
        requires:
          - lint
      - dist:
        requires:
          - test
